export default Object.freeze({
  ROOT_OBJECT: 'ROOT_OBJECT',
  VIEWER_OBJECT: 'VIEWER_OBJECT',
  ENTITY: 'ENTITY',
  ENTITY_SET: 'ENTITY_SET',
  UNION: 'UNION',
  INTERFACE: 'INTERFACE',
  UNION_LIST: 'UNION_LIST',
  INTERFACE_SET: 'INTERFACE_SET',
  INLINE_FRAGMENT_ENTITY: 'INLINE_FRAGMENT_ENTITY',
  INLINE_FRAGMENT_TYPED_OBJECT: 'INLINE_FRAGMENT_TYPED_OBJECT',
  EMBED: 'EMBED',
  EMBED_LIST: 'EMBED_LIST'
});
