export default Object.freeze({
  FETCH_FROM_CACHE_OR_THROW: 'FETCH_FROM_CACHE_OR_THROW',
  FETCH_FROM_CACHE_OR_FALLBACK_NETWORK: 'FETCH_FROM_CACHE_OR_FALLBACK_NETWORK', // default
  FETCH_FROM_CACHE_AND_NETWORK: 'FETCH_FROM_CACHE_AND_NETWORK',
  FETCH_FROM_NETWORK: 'FETCH_FROM_NETWORK'
});
